package com.av.lec16_room;

import android.arch.persistence.room.ColumnInfo;
import android.arch.persistence.room.Entity;
import android.arch.persistence.room.PrimaryKey;

/**
 * Created by Ankit on 13-07-2018.
 */

@Entity(tableName = "task_table")
public class Task {
    @PrimaryKey(autoGenerate = true)
    int id;

    String title;

    String description;

    @ColumnInfo(name = "status")
    boolean isDone;

    public Task(String title, String description, boolean isDone) {// since id is autogenerated
        this.title = title;
        this.description = description;
        this.isDone = isDone;
    }

    public int getId() {
        return id;
    }

    public String getTitle() {
        return title;
    }

    public String getDescription() {
        return description;
    }

    public boolean isDone() {
        return isDone;
    }

    public void setId(int id) {
        this.id = id;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public void setDone(boolean done) {
        isDone = done;
    }

    @Override
    public String toString() {
        return this.id + " " + this.title + " " + this.isDone + " " + this.description;
    }
}
